### ISSUE TITLE
Missing translations for Zend\Validator\Between

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-i18n-resources#5]
[zendframework/zend-validator#174](https://github.com/zendframework/zend-validator/pull/174/files#diff-41891f191ca3a483b5842a36c2d3e0d3R37) introduced 2 new validation messages which are not translated.

---

Originally posted by @BreiteSeite at https://github.com/zendframework/zend-i18n-resources/issues/31

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
